name: Stripes
channels:
  - conda-forge
dependencies:
  - python=3.11
  - iris=3.12
  - xarray
  - zarr
  - gcsfs
  - cmocean
  - astropy

variables:
  PYTHONPATH: /home/users/philip.brohan/Projects/Stripes
# Project directory
  PDIR: /data/scratch/philip.brohan/Stripes
